[pytest]
addopts = --tb=long -vv --junitxml=reports/pytest/results.xml --ignore-glob=scratches/**
log_cli = true
log_level = DEBUG
markers =
    slow
	fbx
	lightweight
filterwarnings = 
# Removed unsupported env_files option (was emitting pytest warning)
pythonpath = 
	tests
testpaths = 
	tests
